### ISSUE TITLE
I don't think this header should be here

### ISSUE THREAD

**Issue by duall** [boblemaire/esp32HTTPrequest#1]
https://github.com/boblemaire/esp32HTTPrequest/blob/92e0522cfe307f03662846bc89e06dd8800b4a8f/esp32HTTPrequest.cpp#L79

**Comment by boblemaire** [comment]
You are correct. I haven't been maintaining this version for some time, and with no feedback assumed it was not being used.  Development has been ongoing as a component of the IoTaWatt ESP32 effort, and that version is working for that purpose.  I've merged that version into Master here.
