### ISSUE TITLE
send(String body) assumes PSRAM is available by calling ps_malloc

### ISSUE THREAD

**Issue by obones** [boblemaire/esp32HTTPrequest#10]
I'm using a ESP32-WROOM32D based board which has no PSRAM installed, nor did I add one to it.
This means that `ps_malloc` is implemented like this:

```c
void IRAM_ATTR *ps_malloc(size_t size){
    return NULL;
}
```

Unfortunately, `esp32HTTPrequest::send(String body)` uses `ps_malloc` which in my case leads to an access violation as it tries to access a null pointer.

Wouldn't it be easier to simply call `_send` like this?

```c
_send(body.c_str(), body.length());
```

This would not require a new allocation, nor require to free it afterwards.

**Comment by boblemaire** [comment]
This illustrates the problem with making changes to accommodate one particular use case.  In my case I switched to ESP32-WROVER with PSRAM and made some quick changes to use the PSRAM. 

The problem with what you suggest is that the data buffer must remain static until the data is transmitted.  Where send is called with char* buffer, it does exactly what you are suggesting.  But with two processors and dozens of tasks, a lot can happen between the time you invoke send(String) and when the data is actually used.  As a class, String variables are automatically deleted when they go out of scope.  Yours may not go out of scope, but it would create a hard to find bug for another user that did not sufficiently appreciate this limitation.

If you feel that your String is sufficiently static that it will endure the life of the request, you can simply do what you suggested on your end with  `send(yourString.c_str(), yourString.length());`

At some point I will change the ps_malloc to capability based allocation to make it work with the WROOM version.

**Comment by obones** [comment]
> The problem with what you suggest is that the data buffer must remain static until the data is transmitted

Well, this is guaranteed by construction in the default mode because `_send` is blocking.
But I agree that this is no longer the case if `_async` is set to `true`.
May the code could check for this and not create a copy if is the transfer is blocking?

**Comment by boblemaire** [comment]
It only blocks the task.  There are two processors and potentially dozens of tasks.

**Comment by obones** [comment]
Yes, I know that, but because the task is blocked, the entire call stack is blocked and so the `String` instance cannot go out of scope, guarantying that the memory is not freed behind the task's back.
But maybe I'm missing something here.
