### ISSUE TITLE
Two warnings with VSCode/PlatformIO

### ISSUE THREAD

**Issue by obones** [boblemaire/esp32HTTPrequest#4]
I'm using this library in a VSCode/PlatformIO project and I get the following two warnings:

* esp32HTTPrequest.cpp
	unused variable '_this' [-Wunused-variable] at line 417, column 23

* esp32HTTPrequest.h
	format '%d' expects argument of type 'int', but argument 5 has type 'char*' [-Wformat=]" at line 40, column 88

The first one makes perfect sense to me because `_this` is indeed not used, but the other one is more of a mystery to me.

In the end, these are not that important anyway so I believe there is no hurry there.

**Comment by boblemaire** [comment]
These should be fixed in 1.1.17
